// This file is auto-generated by FlagControl. Do not edit manually.

import type { FlagControlRegister } from "./types";

export type FlagControlAppFlags = {
    "dark-mode": boolean;
    "app-name": "ebi" | "prince";
    "turnstile": "sdfsdf" | "2ssss" | "" | ({} & string);
};

declare module "./types" {
  interface FlagControlRegister {
    flags: FlagControlAppFlags;
  }
}
