// This file is auto-generated by FlagControl. Do not edit manually.

import type { FlagControlProperties } from "@flagcontrol/core";

export type FlagControlAppFlags = {
    "payment-enabled": boolean;
    "dark-mode": boolean;
};

declare module "@flagcontrol/core" {
  interface FlagControlProperties {
    flags: FlagControlAppFlags;
    contextAttributes: "email" | ({} & string); 
    listKeys:  | ({} & string); 
  }
}
