// This file is auto-generated by FlagControl. Do not edit manually.

import type { FlagControlRegister } from "@flagcontrol/core";

export type FlagControlAppFlags = {
    "aasd": boolean;
};

declare module "@flagcontrol/core" {
  interface FlagControlRegister {
    flags: FlagControlAppFlags;
  }
}
