// This file is auto-generated by FlagControl. Do not edit manually.

import type { FlagControlRegister } from "@flagcontrol/core";

export type FlagControlAppFlags = {
    "go-flag": boolean;
    "prince-sss": "" | ({} & string);
};

declare module "@flagcontrol/core" {
  interface FlagControlRegister {
    flags: FlagControlAppFlags;
  }
}
