// This file is auto-generated by FlagControl. Do not edit manually.

// eslint-disable-next-line @typescript-eslint/no-unused-vars
import type { FlagControlProperties } from "@flagcontrol/core";

export type FlagControlAppFlags = {
    "go-flag": boolean;
    "prince-sss": "" | ({} & string);
};

declare module "@flagcontrol/core" {
  interface FlagControlProperties {
    flags: FlagControlAppFlags;
  }
}
